### ISSUE TITLE
Rest-Client Gem

### ISSUE THREAD

**Issue by Robin481** [looorent/keycloak-api-rails#1]
The function "find_public_keys" uses a RestClient for the call to the public key url.

However this gem does not add the 'rest-client' as a dependency. This leads to the error: uninitialized constant Keycloak::PublicKeyResolver::RestClient

For anyone having this problem add: " gem 'rest-client' " to your gemfile.

Rails Version: 5.2.1
Ruby Version: 2.3.1

**Comment by looorent** [comment]
@Robin481: thanks for your feedback.
I've declared `rest-client` as a dependency and pushed a new version `0.10.2`.
I will probably get rid of `RestClient` in the next versions.
